/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary": "var(--color-primary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary-container": "var(--color-secondary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-dim": "#dcd9d9",
        "primary-fixed-dim": "#ffb4ac",
        "tertiary-container": "#5c5c5c",
        "surface": "var(--color-surface)",
        "on-secondary-fixed": "#241a00",
        "tertiary-fixed-dim": "#c8c6c6",
        "background": "var(--color-surface)",
        "on-primary-fixed": "#410003",
        "surface-container": "var(--color-surface-container)",
        "primary-container": "var(--color-primary-container)",
        "secondary-fixed-dim": "#e9c349",
        "on-error-container": "var(--color-on-error-container)",
        "secondary": "var(--color-secondary)",
        "on-error": "var(--color-on-error)",
        "on-tertiary": "#ffffff",
        "surface-variant": "var(--color-surface-container-highest)",
        "on-tertiary-fixed": "#1b1c1c",
        "error-container": "var(--color-error-container)",
        "inverse-primary": "#ffb4ac",
        "tertiary": "#444545",
        "on-secondary-fixed-variant": "#574500",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-tertiary-container": "#d6d4d4",
        "surface-container-low": "var(--color-surface-container-low)",
        "primary-fixed": "#ffdad6",
        "tertiary-fixed": "#e4e2e2",
        "error": "var(--color-error)",
        "secondary-fixed": "#ffe088",
        "outline": "var(--color-outline)",
        "inverse-surface": "#313030",
        "on-surface": "var(--color-on-surface)",
        "on-secondary": "var(--color-on-secondary)",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-fixed-variant": "#92030f",
        "on-primary": "var(--color-on-primary)",
        "on-background": "var(--color-on-surface)",
        "surface-container-high": "var(--color-surface-container-high)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "max-width": "1200px",
        "margin-mobile": "16px",
        "xs": "4px",
        "unit": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "2xl": "64px",
        "3xl": "96px",
        "4xl": "128px",
        "margin-desktop": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
